# =========================================================================
# 🐧 HYPRLAND CONFIG - MacBook Pro ARM (NixOS Asahi)
# Стандарт синтаксиса: v0.53+ (Legacy windowrulev2 removed)
# =========================================================================

#ПЕРЕМЕННЫЕ И ПРОГРАММЫ ----------------------------------------------------------------------------------------------------------------------------------------------------
$mainMod = SUPER
$terminal = kitty
$menu = wofi --show drun
$fileManager = nautilus

#module
source = ~/.config/hypr/module/in-out.conf
source = ~/.config/hypr/module/exec-once.conf
source = ~/.config/hypr/module/decoration.conf
source = ~/.config/hypr/module/bind.conf
source = ~/.config/hypr/module/windowrule.conf

source = /home/asardiukov/.config/hypr/noctalia/noctalia-colors.conf
