#ПЕРЕМЕННЫЕ И ПРОГРАММЫ ----------------------------------------------------------------------------------------------------------------------------------------------------
$mainMod = SUPER
$terminal = kitty
$menu = wofi --show drun
$fileManager = nautilus
#ГОРЯЧИЕ КЛАВИШИ
bind = $mainMod, RETURN, exec, $terminal
bind = $mainMod, D, exec, $menu
bind = $mainMod, E, exec, kitty --class yazi-fm yazi
bind = $mainMod SHIFT, E, exec, nemo
bind = $mainMod, Q, killactive,
bind = $mainMod, V, togglefloating,
bind = $mainMod, M, exit,
bind = $mainMod, W, exec, zen
bind = $mainMod SHIFT, W, exec, chromium-browser
bind = $mainMod, F, fullscreen, 1
bind = $mainMod SHIFT, F, fullscreen, 0
bind = $mainMod, C, exec, code
bind = $mainMod, N, exec, networkmanager_dmenu 
bind = $mainMod, B, exec, blueman
bind = $mainMod, A, exec, scrcpy -S
# Переключение рабочих столов
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6
bind = $mainMod, 7, workspace, 7
bind = $mainMod, 8, workspace, 8
bind = $mainMod, 9, workspace, 9
bind = $mainMod, S, togglespecialworkspace, magic
# Перемещение окон
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6
bind = $mainMod SHIFT, 7, movetoworkspace, 7
bind = $mainMod SHIFT, 8, movetoworkspace, 8
bind = $mainMod SHIFT, 9, movetoworkspace, 9
bind = $mainMod SHIFT, S, movetoworkspace, special:magic
# Мультимедиа (Звук и Яркость)
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86MonBrightnessUp, exec, brightnessctl set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl set 5%-
# Скриншоты
bind = $mainMod SHIFT, P, exec, grim - | wl-copy
bind = $mainMod SHIFT, O, exec, grim -g "$(slurp)" - | wl-copy
# --- ПЕРЕМЕЩЕНИЕ ФОКУСА (Стрелками) ---
bind = $mainMod, left,  movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up,    movefocus, u
bind = $mainMod, down,  movefocus, d
# --- ПЕРЕМЕЩЕНИЕ ОКОН (Shift + Super + Стрелки) ---
bind = $mainMod SHIFT, left,  movewindow, l
bind = $mainMod SHIFT, right, movewindow, r
bind = $mainMod SHIFT, up,    movewindow, u
bind = $mainMod SHIFT, down,  movewindow, d
# binde означает, что кнопку можно зажать, и яркость будет меняться плавно
binde = SUPER, F1, exec, brightnessctl -d '*kbd_backlight*' set 10%-
binde = SUPER, F2, exec, brightnessctl -d '*kbd_backlight*' set +10%
# Перемещение окон: Super + ЛКМ (Левая кнопка мыши)
bindm = $mainMod, mouse:272, movewindow
# Изменение размера: Super + ПКМ (Правая кнопка мыши)
bindm = $mainMod, mouse:273, resizewindow
