# --- 4. АВТОЗАПУСК ----------------------------------------------------------------------------------------------------------------------------------------------------
exec-once = hyprctl setcursor Bibata-Modern-Classic 24
exec-once = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
exec-once = rclone mount yadisk: ~/YandexDisk --vfs-cache-mode full --daemon
exec-once = udiskie &
#exec-once = noctalia-shell
exec-once = waybar
exec-once = mako &
exec-once = awww-daemon &
exec-once = Throne -tray
exec-once = avizo-service
