
#ВВОД И ЖЕСТЫ ----------------------------------------------------------------------------------------------------------------------------------------------------
input {
    kb_layout = us,ru
    kb_options = grp:caps_toggle
    follow_mouse = 1
    sensitivity = 0
    touchpad {
        natural_scroll = false
        tap-to-click = true
        clickfinger_behavior = true
    }
}

#МОНИТОР (MacBook Pro 16" ProMotion) ----------------------------------------------------------------------------------------------------------------------------------------------------
monitor=eDP-1,3456x2234@120,0x0,2
misc {
    force_default_wallpaper = 0    # Выключает стандартные обои Hyprland
    disable_hyprland_logo = true   # Убирает логотип при загрузке
}
# Главный внешний монитор (Справа): FHD, 75 Гц, масштаб 1
monitor=HDMI-A-1, 1920x1080@75, 1728x0, 1
# Триггер закрытия крышки (выключаем экран ноутбука)
bindl = , switch:on:Apple SMC power/lid events, exec, hyprctl keyword monitor "eDP-1, disable"
# Триггер открытия крышки (включаем экран ноутбука обратно)
bindl = , switch:off:Apple SMC power/lid events, exec, hyprctl keyword monitor "eDP-1, 3456x2234@120, 0x0, 2"

