#НОВЫЕ ПРАВИЛА ОКОН (СТАНДАРТ 0.53+) ----------------------------------------------------------------------------------------------------------------------------------------------------

# Делаем рабочие столы 1-10 постоянными (они не будут исчезать, когда пустые)
workspace = 1, persistent:true
workspace = 2, persistent:true
workspace = 3, persistent:true
workspace = 4, persistent:true
workspace = 5, persistent:true
workspace = 6, persistent:true
workspace = 7, persistent:true
workspace = 8, persistent:true
workspace = 9, persistent:true

# Стол 1: Код
windowrule = workspace 1,match:class ^(kitty)$
windowrule = workspace 1,match:class ^(code)$
windowrule = workspace 1,match:class ^(geany)$
windowrule = workspace 1,match:class ^(chrome-mjoklplbddabcmpepnokjaffbmgbkkgg-Default)$
# Стол 2: Браузер
windowrule = workspace 2,match:class ^(zen)$
windowrule = workspace 2,match:class ^(chromium-browser)$
# Стол 3: ИИ
windowrule = workspace 3,match:class ^(chrome-gemini.google.com__app-Default)$
# Стол 4: Медиа (Читалка и Блокноты)
windowrule = workspace 4,match:class ^(com\.github\.johnfactotum\.Foliate)$
windowrule = workspace 4,match:class ^(net.cozic.joplin_desktop)$
windowrule = workspace 4,match:class ^(obsidian)$
# Стол 5: Файлы
windowrule = workspace 5,match:class ^(yazi-fm)$
windowrule = workspace 5,match:class ^(nemo)$
# Стол 6: YouTube, Cassette
windowrule = workspace 6,match:class ^(FFPWA-01KP855K3GRAXGP73RFK6B78Y6)$
windowrule = workspace 6,match:class ^(space.rirusha.Cassette)$
# Стол 7: Работа
windowrule = workspace 7,match:class ^(chrome-bbbehlpkbdhblohnehmdbmclfkgalkpf-Default)$
windowrule = workspace 7,match:class ^(chrome-kaacbmdkflpbljbdbocghinmafdcmoed-Default)$
# Стол 8: Связь
windowrule = workspace 8,match:class ^(org.telegram.desktop)$
windowrule = workspace 8,match:class ^(chrome-nhkmjnbhpenlpgpejaeojbjfdbhoanjm-Default)$
#---ПЛАВАЮЩИЕ ОКНА (FLOAT RULES) 
#Плавающий режим
windowrule = float 1, match:class ^(calendar-float)$
windowrule = float 1,match:class ^(Bitwarden)$
windowrule = float 1,match:class ^(org\.qbittorrent\.qBittorrent)$
windowrule = float 1,match:class ^(localsend)$
windowrule = float 1,match:class ^(xdg-desktop-portal-gtk)$
windowrule = float 1,match:title ^(Open File)$
windowrule = float 1,match:title ^(Save File)$
windowrule = float 1,match:title ^(Печать)
windowrule = float 1,match:title ^(Print)$
windowrule = float 1,match:title ^(A001)$
windowrule = float 1,match:class ^(float_calcure)
windowrule = float 1,match:class ^(sys-manager)$
windowrule = float 1,match:class ^(.blueman-manager-wrapped)$
#Анимация
windowrule = animation slide right,match:class ^(sys-manager)$
windowrule = animation slide right,match:class ^(.blueman-manager-wrapped)$
#Центрируем
windowrule = center 1,match:class ^(org\.qbittorrent\.qBittorrent)$
windowrule = center 1,match:class ^(Bitwarden)$
windowrule = move 12 47,match:class ^(.scrcpy-wrapped)$
windowrule = move 515 47,match:class ^(float_calcure)$
windowrule = move 1300 60,match:class ^(sys-manager)$
windowrule = move 1110 60,match:class ^(sys-manager)$
windowrule = move 1110 60,match:class ^(.blueman-manager-wrapped)$
#Задаем размер
windowrule = size 1100 700,match:class ^(org\.qbittorrent\.qBittorrent)$ match:title ^(qBittorrent)(.*)$
windowrule = size 450 250,match:class ^(calendar-float)$
windowrule = size 483 1058,match:class ^(.scrcpy-wrapped)$ 
windowrule = size 1200 600,match:class ^(float_calcure)$
windowrule = size 600 1000,match:class ^(sys-manager)$
windowrule = size 600 1000,match:class ^(.blueman-manager-wrapped)$
